#!/bin/bash

mx-run solGS::queryJobs  --data_type genotype  --population_type trial  --args_file /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/geno-data-args_file-141-4aje7 > /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-141-out-QF9X9 2> /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-141-err-pCA2E