---
abstract: 'a hot-deployable variant of Net::Server::PreFork'
author:
  - 'Kazuho Oku'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Server::Simple::CGI: 0
  LWP::Simple: 0
  Test::TCP: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Server-SS-PreFork
no_index:
  directory:
    - inc
    - t
requires:
  Net::Server: 0
  Server::Starter: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
