#!/bin/bash

set -e

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "---------------------------------------------------------"
echo "Building react app"

cd ${script_dir}/react
npm install
npm run build
cd ../

echo -e "---------------------------------------------------------"
echo -e "Symlinking build"

ln -f -s ../react/build/client/react/ mason/react
ln -f -s ../react/build/client/ static/react
