cpanm -L /home/vagrant/cxgn/local-lib/ Algorithm::Combinatorics --force
cpanm -L /home/vagrant/cxgn/local-lib/ Barcode::Code128 --force
cpanm -L /home/vagrant/cxgn/local-lib/ Bio::Chado::Schema --force
cpanm -L /home/vagrant/cxgn/local-lib/ Bio::GMOD::Blast::Graph --force
cpanm -L /home/vagrant/cxgn/local-lib/ Bio::Graphics::FeatureFile --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::Controller::CGIBin --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::Controller::HTML::FormFu --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::Plugin::Authorization::Roles --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::Plugin::SmartURI --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::View::Bio::SeqIO --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::View::Download::CSV --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::View::Email --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::View::HTML::Mason --force
cpanm -L /home/vagrant/cxgn/local-lib/ Catalyst::View::JavaScript::Minifier::XS --force
cpanm -L /home/vagrant/cxgn/local-lib/ CatalystX::GlobalContext --force
cpanm -L /home/vagrant/cxgn/local-lib/ Chart::Clicker --force
cpanm -L /home/vagrant/cxgn/local-lib/ Config::JFDI --force
cpanm -L /home/vagrant/cxgn/local-lib/ DBIx::Class --force
cpanm -L /home/vagrant/cxgn/local-lib/ DBIx::Connector --force
cpanm -L /home/vagrant/cxgn/local-lib/ DateTime::Format::Pg --force
cpanm -L /home/vagrant/cxgn/local-lib/ GD::Graph::bars --force
cpanm -L /home/vagrant/cxgn/local-lib/ GD::Graph::points --force
cpanm -L /home/vagrant/cxgn/local-lib/ GD::Text --force
cpanm -L /home/vagrant/cxgn/local-lib/ HTML::TreeBuilder::XPath --force
cpanm -L /home/vagrant/cxgn/local-lib/ List::AllUtils --force
cpanm -L /home/vagrant/cxgn/local-lib/ List::Compare --force
cpanm -L /home/vagrant/cxgn/local-lib/ Mail::Sendmail --force
cpanm -L /home/vagrant/cxgn/local-lib/ Math::Base36 --force
cpanm -L /home/vagrant/cxgn/local-lib/ MooseX::Declare --force
cpanm -L /home/vagrant/cxgn/local-lib/ MooseX::FollowPBP --force
cpanm -L /home/vagrant/cxgn/local-lib/ MooseX::Object::Pluggable --force
cpanm -L /home/vagrant/cxgn/local-lib/ MooseX::Types::URI --force
cpanm -L /home/vagrant/cxgn/local-lib/ PDF::Create --force
cpanm -L /home/vagrant/cxgn/local-lib/ Spreadsheet::ParseExcel --force
cpanm -L /home/vagrant/cxgn/local-lib/ Spreadsheet::Read --force
cpanm -L /home/vagrant/cxgn/local-lib/ String::Approx --force
cpanm -L /home/vagrant/cxgn/local-lib/ Test::Class --force
cpanm -L /home/vagrant/cxgn/local-lib/ Tie::UrlEncoder --force
cpanm -L /home/vagrant/cxgn/local-lib/ XML::Atom --force
cpanm -L /home/vagrant/cxgn/local-lib/ XML::Feed --force
cpanm -L /home/vagrant/cxgn/local-lib/ XML::Generator --force
cpanm -L /home/vagrant/cxgn/local-lib/ enum --force
