package CXGN::Transformation::AddAutogeneratedNameInfo;

=head1 NAME

CXGN::Transformation::AddAutogeneratedNameInfo - a module to add autogenerated name metadata.

=head1 USAGE


=head1 DESCRIPTION


=head1 AUTHORS

Titima Tantikanjana (tt15@cornell.edu)

=cut

use Moose;
use MooseX::FollowPBP;
use Moose::Util::TypeConstraints;
use Try::Tiny;
use SGN::Model::Cvterm;
use Data::Dumper;
use JSON;


has 'schema' => (
    is => 'rw',
    isa => 'DBIx::Class::Schema',
	predicate => 'has_schema',
	required => 1,
);

has 'dbh' => (
    is  => 'rw',
    predicate => 'has_dbh',
    required => 1,
);

has 'breeding_program_id' => (
    isa =>'Int',
    is => 'rw',
    predicate => 'has_breeding_program_id',
    required => 1,
);

has 'prefix' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_prefix',
    required => 1,
);

has 'current_serial_number' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_prefix',
    required => 1,
);

has 'number_of_digits' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_number_of_digits',
);

has 'description' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_description',
);

has 'added_by' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_added_by',
    required => 1,
);

has 'date' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_date',
);


sub add_info {

    my $self = shift;
    my $schema = $self->get_schema();
    my $breeding_program_id = $self->get_breeding_program_id();
    my $prefix = $self->get_prefix();
    my $current_serial_number = $self->get_current_serial_number();
    my $number_of_digits = $self->get_number_of_digits();
    my $description = $self->get_description();
    my $added_by = $self->get_added_by();;
    my $date = $self->get_date();;
    my $transaction_error;

#    my $coderef = sub {

        my $name_metadata_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property')->cvterm_id;
        my %name_metadata;
        $name_metadata{$prefix}{'current_serial_number'} = $current_serial_number;
        $name_metadata{$prefix}{'number_of_digits'} = $number_of_digits;
        $name_metadata{$prefix}{'description'} = $description;
        $name_metadata{$prefix}{'added_by'} = $added_by;
        $name_metadata{$prefix}{'date'} = $date;

        my $name_metadata_string = encode_json \%name_metadata;
        print STDERR "METADATA =".Dumper($name_metadata_string)."\n";
        my $new_name_metadata = $schema->resultset('Project::Projectprop')->create({
            project_id => $breeding_program_id,
            type_id => $name_metadata_type_id,
            value => $name_metadata_string
        });

#    };

#    try {
#        $schema->txn_do($coderef);
#    } catch {
#        $transaction_error =  $_;
#    };

#    if ($transaction_error) {
#        print STDERR "Transaction error adding autogenerated name metadata: $transaction_error\n";
#        return;
#    }

    return { success=>1};

}



#######
1;
#######
