package CXGN::Transformation::AddAutogeneratedNameInfo;

=head1 NAME

CXGN::Transformation::AddAutogeneratedNameInfo - a module to add autogenerated name metadata.

=head1 USAGE


=head1 DESCRIPTION


=head1 AUTHORS

Titima Tantikanjana (tt15@cornell.edu)

=cut

use Moose;
use MooseX::FollowPBP;
use Moose::Util::TypeConstraints;
use Try::Tiny;
use SGN::Model::Cvterm;
use Data::Dumper;
use JSON;


has 'schema' => (
    is => 'rw',
    isa => 'DBIx::Class::Schema',
	predicate => 'has_schema',
	required => 1,
);

has 'dbh' => (
    is  => 'rw',
    predicate => 'has_dbh',
    required => 1,
);

has 'breeding_program_id' => (
    isa =>'Int',
    is => 'rw',
    predicate => 'has_breeding_program_id',
    required => 1,
);

has 'prefix' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_prefix',
    required => 1,
);

has 'current_serial_number' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_prefix',
    required => 1,
);

has 'number_of_digits' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_number_of_digits',
);

has 'description' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_description',
);

has 'added_by' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_added_by',
    required => 1,
);

has 'date' => (
    isa => 'Str',
    is => 'rw',
    predicate => 'has_date',
);


sub add_info {

    my $self = shift;
    my $schema = $self->get_schema();
    my $breeding_program_id = $self->get_breeding_program_id();
    my $prefix = $self->get_prefix();
    my $current_serial_number = $self->get_current_serial_number();
    my $number_of_digits = $self->get_number_of_digits();
    my $description = $self->get_description();
    my $added_by = $self->get_added_by();;
    my $date = $self->get_date();;
    my $transaction_error;

    my $coderef = sub {

        my $name_metadata_cvterm = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property');
        my %name_metadata;
        $name_metadata{'current_serial_number'} = $current_serial_number;
        $name_metadata{'number_of_digits'} = $number_of_digits;
        $name_metadata{'description'} = $description;
        $name_metadata{'added_by'} = $added_by;
        $name_metadata{'date'} = $date;

        my $stored_name_metadata_string;
        my $new_name_metadata_string;
        my $name_metadata_hash = {};
        my $program = $schema->resultset('Project::Project')->find({ project_id => $breeding_program_id});
        if (!$program) {
            print STDERR "Breeding Program not found!\n";
            return;
        }
        my $metadata_projectprop_rs = $program->projectprops({type_id => $name_metadata_cvterm->cvterm_id});
        if ($metadata_projectprop_rs->count == 1){
            $stored_name_metadata_string = $metadata_projectprop_rs->first->value();
            $name_metadata_hash = decode_json $stored_name_metadata_string;
            print STDERR "PREVIOUS METADATA =".Dumper($name_metadata_hash)."\n";
            $name_metadata_hash->{$prefix} = \%name_metadata;
            $new_name_metadata_string = encode_json $name_metadata_hash;
            print STDERR "UPDATED METADATA =".Dumper($name_metadata_hash)."\n";

            $metadata_projectprop_rs->first->update({value=>$new_name_metadata_string});
        } elsif ($metadata_projectprop_rs->count > 1) {
            print STDERR "More than one found!\n";
            return;
        } else {
            $name_metadata_hash->{$prefix} = \%name_metadata;
            $new_name_metadata_string = encode_json $name_metadata_hash;
            print STDERR "NEW METADATA =".Dumper($name_metadata_hash)."\n";

            $program->create_projectprops({$name_metadata_cvterm->name() => $new_name_metadata_string});
        }
    };

    try {
        $schema->txn_do($coderef);
    } catch {
        $transaction_error =  $_;
    };

    if ($transaction_error) {
        print STDERR "Transaction error adding autogenerated name metadata: $transaction_error\n";
        return;
    }

    return 1;

}



#######
1;
#######
