package CXGN::Transformation::CreateAutogeneratedNames;

=head1 NAME

CXGN::Transformation::CreateAutogeneratedNames - a module to create autogenerated names based on autogenerated name metadata.

=head1 USAGE


=head1 DESCRIPTION


=head1 AUTHORS

Titima Tantikanjana (tt15@cornell.edu)

=cut

use Moose;
use MooseX::FollowPBP;
use Moose::Util::TypeConstraints;
use Try::Tiny;
use CXGN::Stock::StockLookup;
use SGN::Model::Cvterm;
use Data::Dumper;
use JSON;

has 'schema' => (
    is => 'rw',
    isa => 'DBIx::Class::Schema',
	predicate => 'has_schema',
	required => 1,
);

has 'dbh' => (
    is  => 'rw',
    predicate => 'has_dbh',
    required => 1,
);

has 'breeding_program_id' => (
    isa =>'Int',
    is => 'rw',
    predicate => 'has_breeding_program_id',
    required => 1,
);

has 'prefix' => (
    isa =>'Str',
    is => 'rw',
    predicate => 'has_prefix',
    required => 1,
);

has 'number_of_names' => (
    isa => 'Int',
    is => 'rw',
    predicate => 'has_number_of_names',
    required => 1,
);


sub create_names {

    my $self = shift;
    my $schema = $self->get_schema();
    my $breeding_program_id = $self->get_breeding_program_id();
    my $prefix = $self->get_prefix();
    my $number_of_names = $self->get_number_of_names();
    my @autogenerated_names;
    my $name_metadata_hash = {};

    my $autogenerated_name_metadata_cvterm = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property');
    my $autogenerated_name_prefix_cvterm = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property');
    my $program = $schema->resultset('Project::Project')->find({ project_id => $breeding_program_id});
    if (!$program) {
        print STDERR "Breeding Program not found!\n";
        return;
    }

    my $name_metadata_projectprop_rs = $program->projectprops({type_id => $autogenerated_name_metadata_cvterm->cvterm_id});
    if ($name_metadata_projectprop_rs->count == 1){
        my $name_metadata_string = $name_metadata_projectprop_rs->first->value();
        print STDERR "METADATA =".Dumper($name_metadata_string)."\n";
        $name_metadata_hash = decode_json $name_metadata_string;

    } elsif ($name_metadata_projectprop_rs->count > 1) {
        print STDERR "More than one found!\n";
        return;
    }

    my $prefix_metadata = $name_metadata_hash->{$prefix};
    my $current_serial_number = $prefix_metadata->{'current_serial_number'};
    print STDERR "CURRENT SERIAL NUMBER =".Dumper($current_serial_number)."\n";

    my @new_autogenerated_names;
    foreach my $n (1..$number_of_names) {
        my $incremented_number = $n + $current_serial_number;
        push @new_autogenerated_names, $prefix. $incremented_number;
    }
    print STDERR "NEW AUTOGENERATED NAMES =".Dumper(\@new_autogenerated_names)."\n";
    my $new_current_serial_number = $current_serial_number + $number_of_names;
    print STDERR "NEW SERIAL NUMBER =".Dumper($new_current_serial_number)."\n";

    my $new_names_info = {};
    $new_names_info->{'new_autogenerated_names'} = \@new_autogenerated_names;
    $new_names_info->{'new_current_serial_number'} = $new_current_serial_number;

    return $new_names_info;

}



#######
1;
#######
