#!/bin/bash

mx-run solGS::queryJobs  --data_type phenotype  --population_type trial  --args_file /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/pheno-data-args_file-139-3Xd_M > /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/phenotype-data-query-139-out-V97zi 2> /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/phenotype-data-query-139-err-ARdNA