services:
  cap:
    depends_on:
      valkey:
        condition: service_healthy
    image: tiago2/cap:3.1.5
    container_name: cap
    ports:
      - "3000:3000"
    environment:
      ADMIN_KEY: change_admin_password
      REDIS_URL: redis://valkey:6379
    restart: unless-stopped

  valkey:
    image: valkey/valkey:9-alpine
    container_name: cap-valkey
    volumes:
      - valkey-data:/data
    command: valkey-server --save 60 1 --loglevel warning --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  valkey-data:
