package SGN::Controller::Primer3;

=head1 NAME

Primer3 picks primers for PCR reactions, considering as criteria: oligonucleotide melting temperature, size, GC content, primer-dimer possibilities, PCR product size, positional contraints within the source (template) sequence, possibilities for ectopic priming (amplifying the wrong sequence), and many other contraints.

=cut

use Moose;
use namespace::autoclean;
use YAML::Any qw/LoadFile/;

use URI::FromHash 'uri';
use List::Compare;
use File::Temp qw / tempfile /;
use File::Slurp;

use DBI;
use HTML::FormFu;

BEGIN { extends 'Catalyst::Controller' }

=head1 PUBLIC ACTIONS

=head2 index

Public path: /primer3/create

Display a Primer3 input form.

=cut

sub create :Path('/primer3/') :Args(0) {
    my ( $self, $c ) = @_;
	my $form = HTML::FormFu->new(LoadFile($c->path_to(qw{forms primer3 formfu_create.yaml})));

    # Set the template
    $c->stash(template => 'primer3/primer3form.mas',
        form => $form);
}


=head2

Submit input and return results.
    
=cut
    
sub update :Path('/primer3/update') :Args(0) {
    	my ($self, $c) = @_;

	# Get all parameters from the form and store them in their respective variables.
	my $SEQUENCE_EXCLUDED_REGION = $c->request->params->{SEQUENCE_EXCLUDED_REGION};
	my $SEQUENCE_INCLUDED_REGION = $c->request->params->{SEQUENCE_INCLUDED_REGION};
	my $SEQUENCE_PRIMER_REVCOMP = $c->request->params->{SEQUENCE_PRIMER_REVCOMP};
	my $SEQUENCE_FORCE_LEFT_END = $c->request->params->{SEQUENCE_FORCE_LEFT_END};
	my $SEQUENCE_INTERNAL_EXCLUDED_REGION = $c->request->params->{SEQUENCE_INTERNAL_EXCLUDED_REGION};
	my $SEQUENCE_QUALITY = $c->request->params->{SEQUENCE_QUALITY};
	my $SEQUENCE_FORCE_LEFT_START = $c->request->params->{SEQUENCE_FORCE_LEFT_START};
	my $SEQUENCE_INTERNAL_OLIGO = $c->request->params->{SEQUENCE_INTERNAL_OLIGO};
	my $SEQUENCE_START_CODON_POSITION = $c->request->params->{SEQUENCE_START_CODON_POSITION};
	my $SEQUENCE_FORCE_RIGHT_END = $c->request->params->{SEQUENCE_FORCE_RIGHT_END};
	my $SEQUENCE_OVERLAP_JUNCTION_LIST = $c->request->params->{SEQUENCE_OVERLAP_JUNCTION_LIST};
	my $SEQUENCE_TARGET = $c->request->params->{SEQUENCE_TARGET};
	my $SEQUENCE_FORCE_RIGHT_START = $c->request->params->{SEQUENCE_FORCE_RIGHT_START};
	my $SEQUENCE_PRIMER = $c->request->params->{SEQUENCE_PRIMER};
	my $SEQUENCE_TEMPLATE = $c->request->params->{SEQUENCE_TEMPLATE};
	my $SEQUENCE_ID = $c->request->params->{SEQUENCE_ID};
	my $SEQUENCE_PRIMER_PAIR_OK_REGION_LIST = $c->request->params->{SEQUENCE_PRIMER_PAIR_OK_REGION_LIST};
	my $PRIMER_DNA_CONC = $c->request->params->{PRIMER_DNA_CONC};
	my $PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS = $c->request->params->{PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS};
	my $PRIMER_PAIR_WT_PRODUCT_SIZE_GT = $c->request->params->{PRIMER_PAIR_WT_PRODUCT_SIZE_GT};
	my $PRIMER_DNTP_CONC = $c->request->params->{PRIMER_DNTP_CONC};
	my $PRIMER_LOWERCASE_MASKING = $c->request->params->{PRIMER_LOWERCASE_MASKING};
	my $PRIMER_PAIR_WT_PRODUCT_SIZE_LT = $c->request->params->{PRIMER_PAIR_WT_PRODUCT_SIZE_LT};
	my $PRIMER_EXPLAIN_FLAG = $c->request->params->{PRIMER_EXPLAIN_FLAG};
	my $PRIMER_MAX_END_GC = $c->request->params->{PRIMER_MAX_END_GC};
	my $PRIMER_PAIR_WT_PRODUCT_TM_GT = $c->request->params->{PRIMER_PAIR_WT_PRODUCT_TM_GT};
	my $PRIMER_FIRST_BASE_INDEX = $c->request->params->{PRIMER_FIRST_BASE_INDEX};
	my $PRIMER_MAX_END_STABILITY = $c->request->params->{PRIMER_MAX_END_STABILITY};
	my $PRIMER_PAIR_WT_PRODUCT_TM_LT = $c->request->params->{PRIMER_PAIR_WT_PRODUCT_TM_LT};
	my $PRIMER_GC_CLAMP = $c->request->params->{PRIMER_GC_CLAMP};
	my $PRIMER_MAX_GC = $c->request->params->{PRIMER_MAX_GC};
	my $PRIMER_PAIR_WT_PR_PENALTY = $c->request->params->{PRIMER_PAIR_WT_PR_PENALTY};
	my $PRIMER_INSIDE_PENALTY = $c->request->params->{PRIMER_INSIDE_PENALTY};
	my $PRIMER_MAX_HAIRPIN_TH = $c->request->params->{PRIMER_MAX_HAIRPIN_TH};
	my $PRIMER_PAIR_WT_TEMPLATE_MISPRIMING = $c->request->params->{PRIMER_PAIR_WT_TEMPLATE_MISPRIMING};
	my $PRIMER_INTERNAL_DNA_CONC = $c->request->params->{PRIMER_INTERNAL_DNA_CONC};
	my $PRIMER_MAX_LIBRARY_MISPRIMING = $c->request->params->{PRIMER_MAX_LIBRARY_MISPRIMING};
	my $PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH = $c->request->params->{PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH};
	my $PRIMER_INTERNAL_DNTP_CONC = $c->request->params->{PRIMER_INTERNAL_DNTP_CONC};
	my $PRIMER_MAX_NS_ACCEPTED = $c->request->params->{PRIMER_MAX_NS_ACCEPTED};
	my $PRIMER_PICK_ANYWAY = $c->request->params->{PRIMER_PICK_ANYWAY};
	my $PRIMER_INTERNAL_MAX_GC = $c->request->params->{PRIMER_INTERNAL_MAX_GC};
	my $PRIMER_MAX_POLY_X = $c->request->params->{PRIMER_MAX_POLY_X};
	my $PRIMER_PICK_INTERNAL_OLIGO = $c->request->params->{PRIMER_PICK_INTERNAL_OLIGO};
	my $PRIMER_INTERNAL_MAX_HAIRPIN_TH = $c->request->params->{PRIMER_INTERNAL_MAX_HAIRPIN_TH};
	my $PRIMER_MAX_SELF_ANY = $c->request->params->{PRIMER_MAX_SELF_ANY};
	my $PRIMER_PICK_LEFT_PRIMER = $c->request->params->{PRIMER_PICK_LEFT_PRIMER};
	my $PRIMER_INTERNAL_MAX_LIBRARY_MISHYB = $c->request->params->{PRIMER_INTERNAL_MAX_LIBRARY_MISHYB};
	my $PRIMER_MAX_SELF_ANY_TH = $c->request->params->{PRIMER_MAX_SELF_ANY_TH};
	my $PRIMER_PICK_RIGHT_PRIMER = $c->request->params->{PRIMER_PICK_RIGHT_PRIMER};
	my $PRIMER_INTERNAL_MAX_NS_ACCEPTED = $c->request->params->{PRIMER_INTERNAL_MAX_NS_ACCEPTED};
	my $PRIMER_MAX_SELF_END = $c->request->params->{PRIMER_MAX_SELF_END};
	my $PRIMER_PRODUCT_MAX_TM = $c->request->params->{PRIMER_PRODUCT_MAX_TM};
	my $PRIMER_INTERNAL_MAX_POLY_X = $c->request->params->{PRIMER_INTERNAL_MAX_POLY_X};
	my $PRIMER_MAX_SELF_END_TH = $c->request->params->{PRIMER_MAX_SELF_END_TH};
	my $PRIMER_PRODUCT_MIN_TM = $c->request->params->{PRIMER_PRODUCT_MIN_TM};
	my $PRIMER_INTERNAL_MAX_SELF_ANY = $c->request->params->{PRIMER_INTERNAL_MAX_SELF_ANY};
	my $PRIMER_MAX_SIZE = $c->request->params->{PRIMER_MAX_SIZE};
	my $PRIMER_PRODUCT_OPT_SIZE = $c->request->params->{PRIMER_PRODUCT_OPT_SIZE};
	my $PRIMER_INTERNAL_MAX_SELF_ANY_TH = $c->request->params->{PRIMER_INTERNAL_MAX_SELF_ANY_TH};
	my $PRIMER_MAX_TEMPLATE_MISPRIMING = $c->request->params->{PRIMER_MAX_TEMPLATE_MISPRIMING};
	my $PRIMER_PRODUCT_OPT_TM = $c->request->params->{PRIMER_PRODUCT_OPT_TM};
	my $PRIMER_INTERNAL_MAX_SELF_END = $c->request->params->{PRIMER_INTERNAL_MAX_SELF_END};
	my $PRIMER_MAX_TEMPLATE_MISPRIMING_TH = $c->request->params->{PRIMER_MAX_TEMPLATE_MISPRIMING_TH};
	my $PRIMER_PRODUCT_SIZE_RANGE = $c->request->params->{PRIMER_PRODUCT_SIZE_RANGE};
	my $PRIMER_INTERNAL_MAX_SELF_END_TH = $c->request->params->{PRIMER_INTERNAL_MAX_SELF_END_TH};
	my $PRIMER_MAX_TM = $c->request->params->{PRIMER_MAX_TM};
	my $PRIMER_QUALITY_RANGE_MAX = $c->request->params->{PRIMER_QUALITY_RANGE_MAX};
	my $PRIMER_INTERNAL_MAX_SIZE = $c->request->params->{PRIMER_INTERNAL_MAX_SIZE};
	my $PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION = $c->request->params->{PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION};
	my $PRIMER_QUALITY_RANGE_MIN = $c->request->params->{PRIMER_QUALITY_RANGE_MIN};
	my $PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION = $c->request->params->{PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION};
	my $PRIMER_SALT_CORRECTIONS = $c->request->params->{PRIMER_SALT_CORRECTIONS};
	my $PRIMER_MIN_END_QUALITY = $c->request->params->{PRIMER_MIN_END_QUALITY};
	my $PRIMER_SALT_DIVALENT = $c->request->params->{PRIMER_SALT_DIVALENT};
	my $PRIMER_INTERNAL_MAX_TM = $c->request->params->{PRIMER_INTERNAL_MAX_TM};
	my $PRIMER_MIN_GC = $c->request->params->{PRIMER_MIN_GC};
	my $PRIMER_SALT_MONOVALENT = $c->request->params->{PRIMER_SALT_MONOVALENT};
	my $PRIMER_INTERNAL_MIN_GC = $c->request->params->{PRIMER_INTERNAL_MIN_GC};
	my $PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE = $c->request->params->{PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE};
	my $PRIMER_SEQUENCING_ACCURACY = $c->request->params->{PRIMER_SEQUENCING_ACCURACY};
	my $PRIMER_INTERNAL_MIN_QUALITY = $c->request->params->{PRIMER_INTERNAL_MIN_QUALITY};
	my $PRIMER_MIN_QUALITY = $c->request->params->{PRIMER_MIN_QUALITY};
	my $PRIMER_SEQUENCING_INTERVAL = $c->request->params->{PRIMER_SEQUENCING_INTERVAL};
	my $PRIMER_INTERNAL_MIN_SIZE = $c->request->params->{PRIMER_INTERNAL_MIN_SIZE};
	my $PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE = $c->request->params->{PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE};
	my $PRIMER_SEQUENCING_LEAD = $c->request->params->{PRIMER_SEQUENCING_LEAD};
	my $PRIMER_INTERNAL_MIN_TM = $c->request->params->{PRIMER_INTERNAL_MIN_TM};
	my $PRIMER_MIN_SIZE = $c->request->params->{PRIMER_MIN_SIZE};
	my $PRIMER_SEQUENCING_SPACING = $c->request->params->{PRIMER_SEQUENCING_SPACING};
	my $PRIMER_INTERNAL_MISHYB_LIBRARY = $c->request->params->{PRIMER_INTERNAL_MISHYB_LIBRARY};
	my $PRIMER_MIN_THREE_PRIME_DISTANCE = $c->request->params->{PRIMER_MIN_THREE_PRIME_DISTANCE};
	my $PRIMER_TASK = $c->request->params->{PRIMER_TASK};
	my $PRIMER_INTERNAL_OPT_GC_PERCENT = $c->request->params->{PRIMER_INTERNAL_OPT_GC_PERCENT};
	my $PRIMER_MIN_TM = $c->request->params->{PRIMER_MIN_TM};
	my $PRIMER_THERMODYNAMIC_ALIGNMENT = $c->request->params->{PRIMER_THERMODYNAMIC_ALIGNMENT};
	my $PRIMER_INTERNAL_OPT_SIZE = $c->request->params->{PRIMER_INTERNAL_OPT_SIZE};
	my $PRIMER_MISPRIMING_LIBRARY = $c->request->params->{PRIMER_MISPRIMING_LIBRARY};
	my $PRIMER_THERMODYNAMIC_PARAMETERS_PATH = $c->request->params->{PRIMER_THERMODYNAMIC_PARAMETERS_PATH};
	my $PRIMER_INTERNAL_OPT_TM = $c->request->params->{PRIMER_INTERNAL_OPT_TM};
	my $PRIMER_NUM_RETURN = $c->request->params->{PRIMER_NUM_RETURN};
	my $PRIMER_TM_FORMULA = $c->request->params->{PRIMER_TM_FORMULA};
	my $PRIMER_INTERNAL_SALT_DIVALENT = $c->request->params->{PRIMER_INTERNAL_SALT_DIVALENT};
	my $PRIMER_OPT_GC_PERCENT = $c->request->params->{PRIMER_OPT_GC_PERCENT};
	my $PRIMER_WT_END_QUAL = $c->request->params->{PRIMER_WT_END_QUAL};
	my $PRIMER_INTERNAL_SALT_MONOVALENT = $c->request->params->{PRIMER_INTERNAL_SALT_MONOVALENT};
	my $PRIMER_OPT_SIZE = $c->request->params->{PRIMER_OPT_SIZE};
	my $PRIMER_WT_END_STABILITY = $c->request->params->{PRIMER_WT_END_STABILITY};
	my $PRIMER_INTERNAL_WT_END_QUAL = $c->request->params->{PRIMER_INTERNAL_WT_END_QUAL};
	my $PRIMER_OPT_TM = $c->request->params->{PRIMER_OPT_TM};
	my $PRIMER_WT_GC_PERCENT_GT = $c->request->params->{PRIMER_WT_GC_PERCENT_GT};
	my $PRIMER_INTERNAL_WT_GC_PERCENT_GT = $c->request->params->{PRIMER_INTERNAL_WT_GC_PERCENT_GT};
	my $PRIMER_OUTSIDE_PENALTY = $c->request->params->{PRIMER_OUTSIDE_PENALTY};
	my $PRIMER_WT_GC_PERCENT_LT = $c->request->params->{PRIMER_WT_GC_PERCENT_LT};
	my $PRIMER_INTERNAL_WT_GC_PERCENT_LT = $c->request->params->{PRIMER_INTERNAL_WT_GC_PERCENT_LT};
	my $PRIMER_PAIR_MAX_COMPL_ANY = $c->request->params->{PRIMER_PAIR_MAX_COMPL_ANY};
	my $PRIMER_WT_HAIRPIN_TH = $c->request->params->{PRIMER_WT_HAIRPIN_TH};
	my $PRIMER_INTERNAL_WT_HAIRPIN_TH = $c->request->params->{PRIMER_INTERNAL_WT_HAIRPIN_TH};
	my $PRIMER_PAIR_MAX_COMPL_ANY_TH = $c->request->params->{PRIMER_PAIR_MAX_COMPL_ANY_TH};
	my $PRIMER_WT_LIBRARY_MISPRIMING = $c->request->params->{PRIMER_WT_LIBRARY_MISPRIMING};
	my $PRIMER_INTERNAL_WT_LIBRARY_MISHYB = $c->request->params->{PRIMER_INTERNAL_WT_LIBRARY_MISHYB};
	my $PRIMER_PAIR_MAX_COMPL_END = $c->request->params->{PRIMER_PAIR_MAX_COMPL_END};
	my $PRIMER_WT_NUM_NS = $c->request->params->{PRIMER_WT_NUM_NS};
	my $PRIMER_INTERNAL_WT_NUM_NS = $c->request->params->{PRIMER_INTERNAL_WT_NUM_NS};
	my $PRIMER_PAIR_MAX_COMPL_END_TH = $c->request->params->{PRIMER_PAIR_MAX_COMPL_END_TH};
	my $PRIMER_WT_POS_PENALTY = $c->request->params->{PRIMER_WT_POS_PENALTY};
	my $PRIMER_INTERNAL_WT_SELF_ANY = $c->request->params->{PRIMER_INTERNAL_WT_SELF_ANY};
	my $PRIMER_PAIR_MAX_DIFF_TM = $c->request->params->{PRIMER_PAIR_MAX_DIFF_TM};
	my $PRIMER_WT_SELF_ANY = $c->request->params->{PRIMER_WT_SELF_ANY};
	my $PRIMER_INTERNAL_WT_SELF_ANY_TH = $c->request->params->{PRIMER_INTERNAL_WT_SELF_ANY_TH};
	my $PRIMER_WT_SELF_ANY_TH = $c->request->params->{PRIMER_WT_SELF_ANY_TH};
	my $PRIMER_INTERNAL_WT_SELF_END = $c->request->params->{PRIMER_INTERNAL_WT_SELF_END};
	my $PRIMER_PAIR_MAX_LIBRARY_MISPRIMING = $c->request->params->{PRIMER_PAIR_MAX_LIBRARY_MISPRIMING};
	my $PRIMER_WT_SELF_END = $c->request->params->{PRIMER_WT_SELF_END};
	my $PRIMER_INTERNAL_WT_SELF_END_TH = $c->request->params->{PRIMER_INTERNAL_WT_SELF_END_TH};
	my $PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING = $c->request->params->{PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING};
	my $PRIMER_WT_SELF_END_TH = $c->request->params->{PRIMER_WT_SELF_END_TH};
	my $PRIMER_INTERNAL_WT_SEQ_QUAL = $c->request->params->{PRIMER_INTERNAL_WT_SEQ_QUAL};
	my $PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH = $c->request->params->{PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH};
	my $PRIMER_WT_SEQ_QUAL = $c->request->params->{PRIMER_WT_SEQ_QUAL};
	my $PRIMER_INTERNAL_WT_SIZE_GT = $c->request->params->{PRIMER_INTERNAL_WT_SIZE_GT};
	my $PRIMER_PAIR_WT_COMPL_ANY = $c->request->params->{PRIMER_PAIR_WT_COMPL_ANY};
	my $PRIMER_WT_SIZE_GT = $c->request->params->{PRIMER_WT_SIZE_GT};
	my $PRIMER_INTERNAL_WT_SIZE_LT = $c->request->params->{PRIMER_INTERNAL_WT_SIZE_LT};
	my $PRIMER_PAIR_WT_COMPL_ANY_TH = $c->request->params->{PRIMER_PAIR_WT_COMPL_ANY_TH};
	my $PRIMER_WT_SIZE_LT = $c->request->params->{PRIMER_WT_SIZE_LT};
	my $PRIMER_PAIR_WT_COMPL_END = $c->request->params->{PRIMER_PAIR_WT_COMPL_END};
	my $PRIMER_WT_TEMPLATE_MISPRIMING = $c->request->params->{PRIMER_WT_TEMPLATE_MISPRIMING};
	my $PRIMER_PAIR_WT_COMPL_END_TH = $c->request->params->{PRIMER_PAIR_WT_COMPL_END_TH};
	my $PRIMER_WT_TEMPLATE_MISPRIMING_TH = $c->request->params->{PRIMER_WT_TEMPLATE_MISPRIMING_TH};
	my $PRIMER_INTERNAL_WT_TM_GT = $c->request->params->{PRIMER_INTERNAL_WT_TM_GT};
	my $PRIMER_PAIR_WT_DIFF_TM = $c->request->params->{PRIMER_PAIR_WT_DIFF_TM};
	my $PRIMER_WT_TM_GT = $c->request->params->{PRIMER_WT_TM_GT};
	my $PRIMER_INTERNAL_WT_TM_LT = $c->request->params->{PRIMER_INTERNAL_WT_TM_LT};
	my $PRIMER_PAIR_WT_IO_PENALTY = $c->request->params->{PRIMER_PAIR_WT_IO_PENALTY};
	my $PRIMER_WT_TM_LT = $c->request->params->{PRIMER_WT_TM_LT};
	my $PRIMER_LIBERAL_BASE = $c->request->params->{PRIMER_LIBERAL_BASE};
	my $PRIMER_PAIR_WT_LIBRARY_MISPRIMING = $c->request->params->{PRIMER_PAIR_WT_LIBRARY_MISPRIMING};
	

	# Remove all non-alphabetic characters (makes FASTA input ok)
	$SEQUENCE_TEMPLATE =~ s/[^a-zA-Z]*//g;

	# Store Boulder-IO formatted input in text variable.

	my $text =  qq(SEQUENCE_EXCLUDED_REGION=$SEQUENCE_EXCLUDED_REGION
SEQUENCE_INCLUDED_REGION=$SEQUENCE_INCLUDED_REGION
SEQUENCE_PRIMER_REVCOMP=$SEQUENCE_PRIMER_REVCOMP
SEQUENCE_FORCE_LEFT_END=$SEQUENCE_FORCE_LEFT_END
SEQUENCE_INTERNAL_EXCLUDED_REGION=$SEQUENCE_INTERNAL_EXCLUDED_REGION
SEQUENCE_QUALITY=$SEQUENCE_QUALITY
SEQUENCE_FORCE_LEFT_START=$SEQUENCE_FORCE_LEFT_START
SEQUENCE_INTERNAL_OLIGO=$SEQUENCE_INTERNAL_OLIGO
SEQUENCE_START_CODON_POSITION=$SEQUENCE_START_CODON_POSITION
SEQUENCE_FORCE_RIGHT_END=$SEQUENCE_FORCE_RIGHT_END
SEQUENCE_OVERLAP_JUNCTION_LIST=$SEQUENCE_OVERLAP_JUNCTION_LIST
SEQUENCE_TARGET=$SEQUENCE_TARGET
SEQUENCE_FORCE_RIGHT_START=$SEQUENCE_FORCE_RIGHT_START
SEQUENCE_PRIMER=$SEQUENCE_PRIMER
SEQUENCE_TEMPLATE=$SEQUENCE_TEMPLATE
SEQUENCE_ID=$SEQUENCE_ID
SEQUENCE_PRIMER_PAIR_OK_REGION_LIST=$SEQUENCE_PRIMER_PAIR_OK_REGION_LIST
PRIMER_DNA_CONC=$PRIMER_DNA_CONC
PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS=$PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS
PRIMER_PAIR_WT_PRODUCT_SIZE_GT=$PRIMER_PAIR_WT_PRODUCT_SIZE_GT
PRIMER_DNTP_CONC=$PRIMER_DNTP_CONC
PRIMER_LOWERCASE_MASKING=$PRIMER_LOWERCASE_MASKING
PRIMER_PAIR_WT_PRODUCT_SIZE_LT=$PRIMER_PAIR_WT_PRODUCT_SIZE_LT
PRIMER_EXPLAIN_FLAG=$PRIMER_EXPLAIN_FLAG
PRIMER_MAX_END_GC=$PRIMER_MAX_END_GC
PRIMER_PAIR_WT_PRODUCT_TM_GT=$PRIMER_PAIR_WT_PRODUCT_TM_GT
PRIMER_FIRST_BASE_INDEX=$PRIMER_FIRST_BASE_INDEX
PRIMER_MAX_END_STABILITY=$PRIMER_MAX_END_STABILITY
PRIMER_PAIR_WT_PRODUCT_TM_LT=$PRIMER_PAIR_WT_PRODUCT_TM_LT
PRIMER_GC_CLAMP=$PRIMER_GC_CLAMP
PRIMER_MAX_GC=$PRIMER_MAX_GC
PRIMER_PAIR_WT_PR_PENALTY=$PRIMER_PAIR_WT_PR_PENALTY
PRIMER_INSIDE_PENALTY=$PRIMER_INSIDE_PENALTY
PRIMER_MAX_HAIRPIN_TH=$PRIMER_MAX_HAIRPIN_TH
PRIMER_PAIR_WT_TEMPLATE_MISPRIMING=$PRIMER_PAIR_WT_TEMPLATE_MISPRIMING
PRIMER_INTERNAL_DNA_CONC=$PRIMER_INTERNAL_DNA_CONC
PRIMER_MAX_LIBRARY_MISPRIMING=$PRIMER_MAX_LIBRARY_MISPRIMING
PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH=$PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH
PRIMER_INTERNAL_DNTP_CONC=$PRIMER_INTERNAL_DNTP_CONC
PRIMER_MAX_NS_ACCEPTED=$PRIMER_MAX_NS_ACCEPTED
PRIMER_PICK_ANYWAY=$PRIMER_PICK_ANYWAY
PRIMER_INTERNAL_MAX_GC=$PRIMER_INTERNAL_MAX_GC
PRIMER_MAX_POLY_X=$PRIMER_MAX_POLY_X
PRIMER_PICK_INTERNAL_OLIGO=$PRIMER_PICK_INTERNAL_OLIGO
PRIMER_INTERNAL_MAX_HAIRPIN_TH=$PRIMER_INTERNAL_MAX_HAIRPIN_TH
PRIMER_MAX_SELF_ANY=$PRIMER_MAX_SELF_ANY
PRIMER_PICK_LEFT_PRIMER=$PRIMER_PICK_LEFT_PRIMER
PRIMER_INTERNAL_MAX_LIBRARY_MISHYB=$PRIMER_INTERNAL_MAX_LIBRARY_MISHYB
PRIMER_MAX_SELF_ANY_TH=$PRIMER_MAX_SELF_ANY_TH
PRIMER_PICK_RIGHT_PRIMER=$PRIMER_PICK_RIGHT_PRIMER
PRIMER_INTERNAL_MAX_NS_ACCEPTED=$PRIMER_INTERNAL_MAX_NS_ACCEPTED
PRIMER_MAX_SELF_END=$PRIMER_MAX_SELF_END
PRIMER_PRODUCT_MAX_TM=$PRIMER_PRODUCT_MAX_TM
PRIMER_INTERNAL_MAX_POLY_X=$PRIMER_INTERNAL_MAX_POLY_X
PRIMER_MAX_SELF_END_TH=$PRIMER_MAX_SELF_END_TH
PRIMER_PRODUCT_MIN_TM=$PRIMER_PRODUCT_MIN_TM
PRIMER_INTERNAL_MAX_SELF_ANY=$PRIMER_INTERNAL_MAX_SELF_ANY
PRIMER_MAX_SIZE=$PRIMER_MAX_SIZE
PRIMER_PRODUCT_OPT_SIZE=$PRIMER_PRODUCT_OPT_SIZE
PRIMER_INTERNAL_MAX_SELF_ANY_TH=$PRIMER_INTERNAL_MAX_SELF_ANY_TH
PRIMER_MAX_TEMPLATE_MISPRIMING=$PRIMER_MAX_TEMPLATE_MISPRIMING
PRIMER_PRODUCT_OPT_TM=$PRIMER_PRODUCT_OPT_TM
PRIMER_INTERNAL_MAX_SELF_END=$PRIMER_INTERNAL_MAX_SELF_END
PRIMER_MAX_TEMPLATE_MISPRIMING_TH=$PRIMER_MAX_TEMPLATE_MISPRIMING_TH
PRIMER_PRODUCT_SIZE_RANGE=$PRIMER_PRODUCT_SIZE_RANGE
PRIMER_INTERNAL_MAX_SELF_END_TH=$PRIMER_INTERNAL_MAX_SELF_END_TH
PRIMER_MAX_TM=$PRIMER_MAX_TM
PRIMER_QUALITY_RANGE_MAX=$PRIMER_QUALITY_RANGE_MAX
PRIMER_INTERNAL_MAX_SIZE=$PRIMER_INTERNAL_MAX_SIZE
PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION=$PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION
PRIMER_QUALITY_RANGE_MIN=$PRIMER_QUALITY_RANGE_MIN
PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION=$PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION
PRIMER_SALT_CORRECTIONS=$PRIMER_SALT_CORRECTIONS
PRIMER_MIN_END_QUALITY=$PRIMER_MIN_END_QUALITY
PRIMER_SALT_DIVALENT=$PRIMER_SALT_DIVALENT
PRIMER_INTERNAL_MAX_TM=$PRIMER_INTERNAL_MAX_TM
PRIMER_MIN_GC=$PRIMER_MIN_GC
PRIMER_SALT_MONOVALENT=$PRIMER_SALT_MONOVALENT
PRIMER_INTERNAL_MIN_GC=$PRIMER_INTERNAL_MIN_GC
PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE=$PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE
PRIMER_SEQUENCING_ACCURACY=$PRIMER_SEQUENCING_ACCURACY
PRIMER_INTERNAL_MIN_QUALITY=$PRIMER_INTERNAL_MIN_QUALITY
PRIMER_MIN_QUALITY=$PRIMER_MIN_QUALITY
PRIMER_SEQUENCING_INTERVAL=$PRIMER_SEQUENCING_INTERVAL
PRIMER_INTERNAL_MIN_SIZE=$PRIMER_INTERNAL_MIN_SIZE
PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE=$PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE
PRIMER_SEQUENCING_LEAD=$PRIMER_SEQUENCING_LEAD
PRIMER_INTERNAL_MIN_TM=$PRIMER_INTERNAL_MIN_TM
PRIMER_MIN_SIZE=$PRIMER_MIN_SIZE
PRIMER_SEQUENCING_SPACING=$PRIMER_SEQUENCING_SPACING
PRIMER_INTERNAL_MISHYB_LIBRARY=$PRIMER_INTERNAL_MISHYB_LIBRARY
PRIMER_MIN_THREE_PRIME_DISTANCE=$PRIMER_MIN_THREE_PRIME_DISTANCE
PRIMER_TASK=$PRIMER_TASK
PRIMER_INTERNAL_OPT_GC_PERCENT=$PRIMER_INTERNAL_OPT_GC_PERCENT
PRIMER_MIN_TM=$PRIMER_MIN_TM
PRIMER_THERMODYNAMIC_ALIGNMENT=$PRIMER_THERMODYNAMIC_ALIGNMENT
PRIMER_INTERNAL_OPT_SIZE=$PRIMER_INTERNAL_OPT_SIZE
PRIMER_MISPRIMING_LIBRARY=$PRIMER_MISPRIMING_LIBRARY
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=$PRIMER_THERMODYNAMIC_PARAMETERS_PATH
PRIMER_INTERNAL_OPT_TM=$PRIMER_INTERNAL_OPT_TM
PRIMER_NUM_RETURN=$PRIMER_NUM_RETURN
PRIMER_TM_FORMULA=$PRIMER_TM_FORMULA
PRIMER_INTERNAL_SALT_DIVALENT=$PRIMER_INTERNAL_SALT_DIVALENT
PRIMER_OPT_GC_PERCENT=$PRIMER_OPT_GC_PERCENT
PRIMER_WT_END_QUAL=$PRIMER_WT_END_QUAL
PRIMER_INTERNAL_SALT_MONOVALENT=$PRIMER_INTERNAL_SALT_MONOVALENT
PRIMER_OPT_SIZE=$PRIMER_OPT_SIZE
PRIMER_WT_END_STABILITY=$PRIMER_WT_END_STABILITY
PRIMER_INTERNAL_WT_END_QUAL=$PRIMER_INTERNAL_WT_END_QUAL
PRIMER_OPT_TM=$PRIMER_OPT_TM
PRIMER_WT_GC_PERCENT_GT=$PRIMER_WT_GC_PERCENT_GT
PRIMER_INTERNAL_WT_GC_PERCENT_GT=$PRIMER_INTERNAL_WT_GC_PERCENT_GT
PRIMER_OUTSIDE_PENALTY=$PRIMER_OUTSIDE_PENALTY
PRIMER_WT_GC_PERCENT_LT=$PRIMER_WT_GC_PERCENT_LT
PRIMER_INTERNAL_WT_GC_PERCENT_LT=$PRIMER_INTERNAL_WT_GC_PERCENT_LT
PRIMER_PAIR_MAX_COMPL_ANY=$PRIMER_PAIR_MAX_COMPL_ANY
PRIMER_WT_HAIRPIN_TH=$PRIMER_WT_HAIRPIN_TH
PRIMER_INTERNAL_WT_HAIRPIN_TH=$PRIMER_INTERNAL_WT_HAIRPIN_TH
PRIMER_PAIR_MAX_COMPL_ANY_TH=$PRIMER_PAIR_MAX_COMPL_ANY_TH
PRIMER_WT_LIBRARY_MISPRIMING=$PRIMER_WT_LIBRARY_MISPRIMING
PRIMER_INTERNAL_WT_LIBRARY_MISHYB=$PRIMER_INTERNAL_WT_LIBRARY_MISHYB
PRIMER_PAIR_MAX_COMPL_END=$PRIMER_PAIR_MAX_COMPL_END
PRIMER_WT_NUM_NS=$PRIMER_WT_NUM_NS
PRIMER_INTERNAL_WT_NUM_NS=$PRIMER_INTERNAL_WT_NUM_NS
PRIMER_PAIR_MAX_COMPL_END_TH=$PRIMER_PAIR_MAX_COMPL_END_TH
PRIMER_WT_POS_PENALTY=$PRIMER_WT_POS_PENALTY
PRIMER_INTERNAL_WT_SELF_ANY=$PRIMER_INTERNAL_WT_SELF_ANY
PRIMER_PAIR_MAX_DIFF_TM=$PRIMER_PAIR_MAX_DIFF_TM
PRIMER_WT_SELF_ANY=$PRIMER_WT_SELF_ANY
PRIMER_INTERNAL_WT_SELF_ANY_TH=$PRIMER_INTERNAL_WT_SELF_ANY_TH
PRIMER_WT_SELF_ANY_TH=$PRIMER_WT_SELF_ANY_TH
PRIMER_INTERNAL_WT_SELF_END=$PRIMER_INTERNAL_WT_SELF_END
PRIMER_PAIR_MAX_LIBRARY_MISPRIMING=$PRIMER_PAIR_MAX_LIBRARY_MISPRIMING
PRIMER_WT_SELF_END=$PRIMER_WT_SELF_END
PRIMER_INTERNAL_WT_SELF_END_TH=$PRIMER_INTERNAL_WT_SELF_END_TH
PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING=$PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING
PRIMER_WT_SELF_END_TH=$PRIMER_WT_SELF_END_TH
PRIMER_INTERNAL_WT_SEQ_QUAL=$PRIMER_INTERNAL_WT_SEQ_QUAL
PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH=$PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH
PRIMER_WT_SEQ_QUAL=$PRIMER_WT_SEQ_QUAL
PRIMER_INTERNAL_WT_SIZE_GT=$PRIMER_INTERNAL_WT_SIZE_GT
PRIMER_PAIR_WT_COMPL_ANY=$PRIMER_PAIR_WT_COMPL_ANY
PRIMER_WT_SIZE_GT=$PRIMER_WT_SIZE_GT
PRIMER_INTERNAL_WT_SIZE_LT=$PRIMER_INTERNAL_WT_SIZE_LT
PRIMER_PAIR_WT_COMPL_ANY_TH=$PRIMER_PAIR_WT_COMPL_ANY_TH
PRIMER_WT_SIZE_LT=$PRIMER_WT_SIZE_LT
PRIMER_PAIR_WT_COMPL_END=$PRIMER_PAIR_WT_COMPL_END
PRIMER_WT_TEMPLATE_MISPRIMING=$PRIMER_WT_TEMPLATE_MISPRIMING
PRIMER_PAIR_WT_COMPL_END_TH=$PRIMER_PAIR_WT_COMPL_END_TH
PRIMER_WT_TEMPLATE_MISPRIMING_TH=$PRIMER_WT_TEMPLATE_MISPRIMING_TH
PRIMER_INTERNAL_WT_TM_GT=$PRIMER_INTERNAL_WT_TM_GT
PRIMER_PAIR_WT_DIFF_TM=$PRIMER_PAIR_WT_DIFF_TM
PRIMER_WT_TM_GT=$PRIMER_WT_TM_GT
PRIMER_INTERNAL_WT_TM_LT=$PRIMER_INTERNAL_WT_TM_LT
PRIMER_PAIR_WT_IO_PENALTY=$PRIMER_PAIR_WT_IO_PENALTY
PRIMER_WT_TM_LT=$PRIMER_WT_TM_LT
PRIMER_LIBERAL_BASE=$PRIMER_LIBERAL_BASE
PRIMER_PAIR_WT_LIBRARY_MISPRIMING=$PRIMER_PAIR_WT_LIBRARY_MISPRIMING
=
);
	
	my $filename = "primer3.txt";
	my $tempdir = File::Spec->catfile($c->config->{basepath}, $c->tempfiles_subdir('primer3'), $filename);


	my @text = split("\n", $text);
	my $filteredtext;
	foreach my $item (@text) {
		if ($item !~ m/=$/) {
			$filteredtext .= $item."\n";
		}
	}
	$filteredtext .= "=";

	write_file($tempdir, $filteredtext);

	system("primer3_core < $tempdir > $tempdir.results");

	open (RESULTS, "$tempdir.results");
	my %results;
	while (<RESULTS>) {
		chomp;
		my @stuff = split(/=/, $_);
		$results{$stuff[0]} = $stuff[1];
	}
	close (RESULTS);
	
        $c->stash(template => 'primer3/primer3results.mas',
		  resultshash => \%results		
	);
    }



__PACKAGE__->meta->make_immutable;
