package SGN::Controller::Transformation;

use Moose;
use URI::FromHash 'uri';
use SGN::Model::Cvterm;
use CXGN::People::Person;
use Data::Dumper;
use CXGN::Transformation::Transformation;

BEGIN { extends 'Catalyst::Controller'; }


sub transformation_page : Path('/transformation') Args(1) {
    my $self = shift;
    my $c = shift;
    my $id = shift;
    my $schema = $c->dbic_schema("Bio::Chado::Schema");
    my $dbh = $c->dbc->dbh;
    my $transformation_stock_type_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'transformation', 'stock_type')->cvterm_id();

    my $transformation = $schema->resultset("Stock::Stock")->find( { stock_id => $id, type_id => $transformation_stock_type_id } );

    my $transformation_id;
    my $transformation_name;
	if (!$transformation) {
    	$c->stash->{template} = '/generic_message.mas';
    	$c->stash->{message} = 'The requested transformation does not exist.';
    	return;
    } else {
        $transformation_id = $transformation->stock_id();
        $transformation_name = $transformation->uniquename();
    }

    my $transformation_obj = CXGN::Transformation::Transformation->new({schema=>$schema, dbh=>$dbh, transformation_stock_id=>$transformation_id});
    my $info = $transformation_obj->get_transformation_info();
    my $plant_material = qq{<a href="/stock/$info->[0]->[0]/view">$info->[0]->[1]</a>};
    my $vector_construct = qq{<a href="/stock/$info->[0]->[2]/view">$info->[0]->[3]</a>};
    my $transformation_notes = $info->[0]->[4];

    my $updated_status_type = $info->[0]->[5];
    my $completed_metadata;
    my $terminated_metadata;
    if ($updated_status_type eq 'terminated_metadata') {
        $updated_status_type = '<span style="color:red">'.'TERMINATED'.'</span>';
        $terminated_metadata = 1;
    } elsif ($updated_status_type eq 'completed_metadata') {
        $updated_status_type = '<span style="color:red">'.'COMPLETED'.'</span>';
        $completed_metadata = 1;
    }

    my $updated_status_string;
    if ($updated_status_type) {
        my $updated_status = CXGN::Stock::Status->new({ bcs_schema => $schema, parent_id => $transformation_id, completed_metadata => $completed_metadata, terminated_metadata => $terminated_metadata});
        my $updated_status_info = $updated_status->get_status_details();
        my $person_id = $updated_status_info->[0];
        my $person= CXGN::People::Person->new($dbh, $person_id);
        my $person_name=$person->get_first_name()." ".$person->get_last_name();
        my $operator_info = "Updated by". ":"."".$person_name;
        my $date_info = "Updated Date". ":"."".$updated_status_info->[1];
        my $reason_info = "Comments". ":"."".$updated_status_info->[2];
        my @all_info = ($operator_info, $date_info, $reason_info);
        my $all_info_string = join("<br>", @all_info);
        $updated_status_string = '<span style="color:red">'.$all_info_string.'</span>';
    }

    my $project_info = $transformation_obj->get_associated_projects();
    my $project_id = $project_info->[0]->[0];
    my $project_name = $project_info->[0]->[1];
    my $program_id = $project_info->[0]->[2];
    my $project_link = qq{<a href="/breeders/trial/$project_id">$project_name</a>};

    my $name_prefix_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_prefix', 'project_property')->cvterm_id();
    my $name_prefix_rs = $schema->resultset("Project::Projectprop")->find ({
        project_id =>  $project_id,
        type_id => $name_prefix_cvterm_id
    });

    if($name_prefix_rs) {
        my $prefix = $name_prefix_rs->value;
        $c->stash->{prefix} = $prefix;
    }

    my $identifier_link;
    my $tracking_transformation = $c->config->{tracking_transformation};
    if ($tracking_transformation) {
        my $tracking_info = $transformation_obj->get_tracking_identifier();
        my $identifier_id = $tracking_info->[0]->[0];
        my $identifier_name = $tracking_info->[0]->[1];
        $identifier_link = qq{<a href="/activity/details/$identifier_id">$identifier_name</a>};
    }

    $c->stash->{transformation_id} = $transformation_id;
    $c->stash->{transformation_name} = $transformation_name;
    $c->stash->{plant_material} = $plant_material;
    $c->stash->{vector_construct} = $vector_construct;
    $c->stash->{transformation_notes} = $transformation_notes;
    $c->stash->{updated_status_type} = $updated_status_type;
    $c->stash->{updated_status_string} = $updated_status_string;
    $c->stash->{user_id} = $c->user ? $c->user->get_object()->get_sp_person_id() : undef;
    $c->stash->{identifier_link} = $identifier_link;
    $c->stash->{project_link} = $project_link;
    $c->stash->{program_id} = $program_id;
    $c->stash->{template} = '/transformation/transformation.mas';

}


1;
