use strict;
use CXGN::Page;
my $page=CXGN::Page->new('200410.html','html2pl converter');
my $stylesheet=<<END_STYLESHEET;
<style type="text/css">
<!--
    body {
        color: #000000;
        background-color: #ffffff;
    }

    p {
        margin-left: 40px;
        text-align: justify;
    }

    .footnote {
        font-size: small;
        /*width: 700px;*/
        text-align:center;
    }

    .bibliography {
        text-indent: -20px;
    }
-->
</style>
END_STYLESHEET
$page->header('The Botella Lab', undef, $stylesheet);
print<<END_HEREDOC;

  <center>
    <h1>The Botella Lab</h1>
  </center>

  <p class="footnote"><img src="/static_content/community/feature/200410.jpg" border="0" width="579"
  height="384" alt="The Botella Lab" /><br />
  From left to right: Upper row: David Pos&eacute;, Maria
  Jos&eacute;, Itziar Castanedo, Karen Merchante, Ver&oacute;nica
  Gonz&acute;lez, Sonia Osorio Lower row: Victoriano Valpuesta,
  Eduardo Gross, Miguel A. Botella, Eduardo Cruz, Irene Araguez,
  Abel Rosado, Aureliano Bombarely</p>

  <h2>Research Interests</h2>

  <p>Only a reduced number of genes have been identified as
  critical for plant salt and drought tolerance. Using a genetic
  approach we have identified several tomato mutants (tss)
  hypersensitive to NaCl as well as 1 tomato (tos1) mutant
  specifically hypersensitive to drought stress. In our laboratory
  we use a combination of physiology, electrophysiology and
  molecular techniques in the characterization of these tomato
  mutants in order to define genes and processes important for salt
  and drought tolerance in plants. We are in the process of cloning
  some of these genes.</p>

  <p>We are also using Arabidopsis in the identification of
  additional genes that are essential for salt and drought stress.
  In collaboration with Dr. Hasegawa we have identified a number of
  T-DNA mutants that are hypersensitive to salt and osmotic stress.
  We have identified the genes affected and we are working in the
  characterization of these mutants. We work together with Dr.
  Victoriano Valpuesta and his group and we are also interested in
  fruit ripening in tomato and strawberry using genomic approaches.
  We have identified an alternative pathway for vitamin C
  biosynthesis in strawberry fruits. In this pathway, the
  biosynthesis of vitamin C in ripe strawberry fruits, which are
  rich in this compound, occurs through D-galacturonic acid, the
  main constituent of cell-wall pectins. We have cloned a key gene
  of this pathway, GalUR, encoding a protein with NADPH-dependent
  D-galacturonate reductase activity that is specifically expressed
  in ripe strawberry fruits. We are interested in determine how
  universal is this pathway in other species including tomato.</p>

  <p>Dr. Botella is Professor of the University of M&aacute;laga
  (Spain) since 1999 and one of the directors of the Laboratorio de
  Biotecnolog&iacute;a de Plantas (Plant Biotechnology Laboratory)
  together with <a href="mailto:Valpuesta\@uma.es">Dr. Valpuesta</a>. He
  obtained his Ph.D. at the University of M&aacute;laga in 1994
  spending some periods during his doctorate at Purdue University.
  After his Thesis, Dr. Botella worked as a posdoct in Purdue
  University under the supervision of Dr. Paul M. Hasegawa with the
  main focus on cysteine proteinase inhibitors. Later he spent 4
  years in the Sainsbury Laboratory (John Innes Centre) under the
  supervision of Dr. Jonathan D.G. Jones working on Arabidopsis
  Resistant Genes.</p>

  <h2>Contact Information</h2>

  <p>University of Malaga<br />
  Dep. Biolog&iacute;a Molecular y Bioqu&iacute;mica<br />
  Facultad de Ciencias<br />
  Campus de Teatinos s/n<br />
  29071 M&aacute;laga<br />
  Spain</p>

  <h2>Selected Publications</h2>

  <p class="bibliography">Borsani O, Valpuesta V, Botella MA (2001)
  Evidence for a role of salicylic acid in the oxidative damage
  generated by NaCl and osmotic stress in Arabidopsis seedlings.
  Plant Physiol 126: 1024-1030</p>

  <p class="bibliography">Borsani O, Cuartero J, Fernandez JA,
  Valpuesta V, Botella MA (2001) Identification of two loci in
  tomato reveals distinct mechanisms for salt tolerance. Plant Cell
  13: 873-887</p>

  <p class="bibliography">Borsani O, Cuartero J, Valpuesta V,
  Botella MA (2002) Tomato tos1 mutation identifies a gene
  essential for osmotic tolerance and abscisic acid sensitivity.
  Plant Journal 32: 905-914</p>

  <p class="bibliography">Gonzalez-Lamothe R, Segura R, Trapero A,
  Baldoni L, Botella MA, Valpuesta V (2002) Phylogeny of the fungus
  Spilocaea oleagina, the causal agent of peacock leaf spot in
  olive. FEMS Microbiology Lett 210: 149-155</p>

  <p class="bibliography">Borsani, O., Valpuesta, V., and Botella,
  M.A. Developing salt tolerance plants in a new century: a
  molecular biology approach (Review). Plant Cell Tissue and Organ
  Culture 73: 101-115</p>

  <p class="bibliography">Agius F, Gonzalez-Lamothe R, Caballero
  JL, Munoz-Blanco J, Botella MA, Valpuesta V (2003) Engineering
  increased vitamin C levels in plants by overexpression of a
  D-galacturonic acid reductase. Nature Biotechnology 21:
  177-181</p>

  <p class="bibliography">Rubio L, Rosado A, Linares-Rueda A,
  Borsani O, Garc&iacute;a-S&aacute;nchez MJ, Valpuesta V,
  Fern\341ndez JA, Botella MA. (2004) Regulation of K+ Transport in
  Tomato Roots by the TSS1 Locus. Implications in Salt Tolerance.
  Plant Physiology 134: 452-459</p>

  <p class="bibliography">Castillejo C, Delafuente JI, Iannetta P,
  Botella MA and Victoriano Valpuesta. (2004). Pectin esterase gene
  family in strawberry fruit. Study of FaPE1, a ripening-specific
  isoform. Journal Experimental Botany. 55: 909-918.</p>

  <p class="bibliography">Valpuesta V, Botella MA. (2004)
  Biosynthesis of L-ascorbic acid in plants: New pathways for an
  old antioxidant. Trends in Plant Science. In press.</p>

  <p class="bibliography">Agius F, Amaya I, Botella MA, Valpuesta
  V. (2004) Functional analysis of homologous and heterologous
  promoters in strawberry fruits using transient expression.
  Journal Experimental Botany. In press.</p>
END_HEREDOC
$page->footer();
