
use strict;
use CXGN::Page;
use CXGN::Page::FormattingHelpers qw / page_title_html /;

my $page = CXGN::Page->new();
$page->header();
my $title = page_title_html("Feature: The De Koeyer Lab");

my $photo_dir = "/static_content/community/feature";

print <<HTML;

$title

<center><img src="$photo_dir/200706-01.jpg" alt="De Koeyer Lab Photo" />
<p class="tinytype">
Back row, left to right: R. Griffiths, L. Nolan, M. Lag&uuml;e, D. De Koeyer, S. Whitney<br />
Front row, left to right: K. Douglass, Y. Song.
</p>
</center>

<p>Our lab is part of the Agriculture and Agri-Food Canada (AAFC) Potato Research Centre in Fredericton, New Brunswick, Canada.  Our on-going research focuses on the application of genomics and bioinformatics to potato improvement.</p>

<p>Our bioinformatics resources were initially established through the <a href="http://www.cpgp.ca">Canadian Potato Genome Project</a> (principle investigators Sharon Regan and Barry Flinn) funded by Genome Canada, Atlantic Canada Opportunities Agency, and the New Brunswick Department of Agriculture and Aquaculture.  We established a bioinformatics pipeline for the analysis of potato Expressed Sequence Tags (ESTs) generated by the Canadian Potato Genome Project, the Institute for Genomics Research , and other international collaborators.  We were an integral part of the Potato Oligo Chip Initiative (POCI) consortium led by Dr. Christian Bachem, Wageningen University, which developed a 44K 60-mer Agilent microarray chip. This chip is being used by consortium members in several countries for gene expression profiling experiments.  The Canadian Potato Genome Project also developed a large collection of activation-tagged potato lines.</p>

<p>Our main research interest currently is the development of bioinformatics and molecular tools for polymorphism discovery.  We have developed a pipeline for the identification of single nucleotide polymorphisms (SNP) and haplotypes within potato unigenes.  Concurrently with the bioinformatics work on polymorphism discovery, we are adopting high-resolution DNA-melting with an Idaho technology Lightscanner instrument for variant scanning and genotyping.  This approach has proven successful for identifying distinct genotypes in homozygous lines, differentiating heterozygous and homozygous lines, and determining the genotypes of both diploid and tetraploid lines.  This technology has the potential to replace conventional gel electrophoresis marker assays.</p>



<table width="100%" cellpadding="10">
<tr><td style="text-align:center; vertical-align:middle">
<img src="$photo_dir/200706-02.jpg" alt="shifted melting curves"><br />
<p class="tinytype">
<strong>Figure 1.</strong> Lightscanner melting curves of the PCR products of four tetraploid potato varieties.  The red lines represent 3 replicates samples of a homozygote; the grey lines two different varieties with the same heterozygous genotype (3 samples each); and the blue lines represent 3 samples of another heterozygous genotype.
</p>
</td></tr>
</table>


<p>We also participate in collaborative research on genetic mapping of common scab (in collaboration with Claudia Goyer), after-cooking darkening (Gefu-Wang-Pruski; Nova Scotia Agricultural College), cold-sweetening (Xiu-Qing Li), and Colorado potato beetle (Yvan Pelletier) resistance genes and quantitative trait loci using simple-sequence repeat and SNP markers.  We have initiated pilot marker-assisted selection projects for PVY resistance, late blight resistance, <em>Verticillium</em> wilt resistance, and tuber-quality traits in collaboration with AAFC potato breeders.  Our lab is also involved in microarray data analyses and other aspects of bioinformatics for functional genomics research.</p>

<p>The final and more applied aspects of our work involve developing informatics tools for the potato breeding program and insect resistant germplasm.  Potato breeders, like genomics researchers, generate vast quantities of data.  Information management systems for breeding programs can improve efficiency as well as contribute to improved decisions related to advancing lines or selecting parents. Mining of breeding data can benefit both breeders and genomics researchers and the development of tools to integrate breeding and genomics data is a long-term goal of our research program.</p>

<p>Wild <em>Solanum</em> species hold a wealth of un-tapped beneficial diversity.  We have been involved in a small germplasm enhancement program to introgress insect resistance into cultivated potato germplasm.  A success story to date has been the use of <em>S. oplocense</em> as a source of resistance to Colorado potato beetle.  Work is continuing to improve the adaptation of this material to the long-day conditions of Canada; however, unexpectedly, the BC1 generation has exceptional processing quality characteristics.</p>


<table width="100%" cellpadding="10">

<tr><td style="text-align:center; vertical-align:middle">
<img src="$photo_dir/200706-03.jpg" alt="potato chips following"><br />
<img src="$photo_dir/200706-04.jpg" alt="storage and defoliation"><br />

<p class="tinytype">
<strong>Figure 2.</strong> Potato chips following 4 months of 7&deg;C storage and defoliation in field by CPB.  The left photos represent resistant BC<sub>1</sub> lines derived from <em>S. oplocense</em>, and the right photos represent the susceptible <em>S. tuberosum</em> variety, Shepody.
</p>

</td></tr>
</table>

<p>The research described above is part of a National AAFC project that I am principal investigator for, titled: &ldquo;Genomics approaches to potato improvement&rdquo;. Collaborators on the project include Drs. H.W. (Bud) Platt (Charlottetown); Claudia Goyer, Xiu-Qing Li, Agnes Murphy, Xianzhou Nie, Helen Tai, Richard Tarn, and Bernie Zebarth (Fredericton); Qiang Liu (Guelph); and Benoit Bizimungu, Qin Chen, and Larry Kawchuk (Lethbridge).  External funding has been provided by the Canada-New Brunswick Embracing Innovation in Agriculture program (New Brunswick Department of Agriculture and Aquaculture) for another current project titled  &ldquo;Genomics-assisted breeding resources for potato improvement&rdquo;.  In collaboration with Dr. Yvan Pelletier, funding for the development of insect resistance germplasm has been provided by the potato industry from Canada and France.</p>

<div style='clear:all;width:100%'>&nbsp;</div>
<p>
<b><u>Contact Information</u></b><br />
Dr. David De Koeyer<br />
Research Scientist/Chercheur<br />
Agriculture and Agri-Food Canada/Agriculture et Agroalimentaire Canada<br />
Telephone/T&eacute;l&eacute;phone: 506-452-4885<br />
Facsimile/T&eacute;l&eacute;copieur: 506-452-3316<br />
P.O. Box 20280/C.P. 20280<br />
850 Lincoln Road/ 850, chemin Lincoln<br />
Fredericton, New Brunswick/Fredericton (Nouveau Brunswick)<br />
CANADA<br />
E3B 4Z7<br />
email: dekoeyerd\@agr.gc.ca
</p>
<img src="$photo_dir/200706-05.jpg" alt="Agriculture and Agri-Food Canada"><br />

<p>
<b><u>Selected Publications</u></b>
<ul style="list-style:none">
<li>X.-Q. Li, R. Griffiths, M. Lag&uuml;e, D. DeKoeyer, C. Rothwell, M. Haroon, B. Stevens, C. Xu, V. Gustafson, M. Bonierbale, S. Regan, and B. Flinn. 2007. EST sequencing and analysis from cold-stored and reconditioned potato tubers.  Acta Horticulturae (in press).</li>
<li>Pelletier, Y., C. Clark, and D. De Koeyer. 2007. Level and genetic variability of resistance to the Colorado potato beetle (Leptinotarsa decemlineata (Say)) in wild Solanum species. Am. J. Potato Res. (in press).</li>
<li>Gustafson, V., S. Mallubhotla, J. MacDonnell, M. Sanyal-Bagchi, B. Chakravarty, G. Wang-Pruski, C. Rothwell, P. Audy, D. De Koeyer, M. Siahbazi, B. Flinn, and S. Regan. 2006. Transformation and plant regeneration from leaf explants of Solanum tuberosum L. cv. 'Shepody'. Plant Cell Tissue Organ Cult. 85: 361-366.</li>
<li>Regan, S., V. Gustafson, S. Mallubhotla, B. Chakravarty, M. Bagchi, M. Siahbazi, C. Rothwell, R. Sardana, C. Goyer, P. Audy, X.-Q. Li, G. Wang-Pruski, , D. De Koeyer, and B. Flinn.  2005. Finding the perfect potato: using functional genomics to improve disease resistance and tuber quality traits. Can. J. Plant Path. 28: s247-s255.</li>
<li>Flinn, B., C. Rothwell, R. Griffiths, M. Lague, D. De Koeyer, R. Sardana, P. Audy, C. Goyer, X.-Q. Li, G. Wang-Pruski, and S. Regan.  2005. Potato Expressed Sequence Tag Generation and Analyses Using Standard and Unique cDNA Libraries. Plant Mol. Biol. 59: 405-431.</li>
<li>De Koeyer, D.L., N.A. Tinker, C.P. Wight, J. Deyl, V.D. Burrows, L.S. O&rsquo;Donoughue, A. Lybaert, S.J. Molnar, K.C. Armstrong, G. Fedak, D.M. Wesenberg, B.G. Rossnagel, A.R. McElroy.  2004.  A molecular linkage map with associated QTLs from a hulless x covered spring oat population.  Theor. Appl. Genet. 108:1285-1298.</li>
</ul></p>

HTML

$page->footer();
