use strict;
use CXGN::Tools::File;
use CXGN::Page;
use CXGN::VHost;
my $vhost_conf=CXGN::VHost->new();
my $documents_folder=$vhost_conf->get_conf('basepath').$vhost_conf->get_conf('documents_subdir');
my $page=CXGN::Page->new('Featured SOL Community Labs','john');
my $LABS=CXGN::Tools::File::file_contents("$documents_folder/labs.txt")||'';
$page->header();
print $LABS;
$page->footer();
