#!/bin/bash

mx-run solGS::queryJobs  --data_type phenotype  --population_type trial  --args_file /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/pheno-data-args_file-139-b7R2l > /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/phenotype-data-query-139-out-sJ9pR 2> /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/phenotype-data-query-139-err-0VXMF