#!/bin/bash

mx-run solGS::queryJobs  --data_type genotype  --population_type trial  --args_file /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/geno-data-args_file-139-RCtQl > /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-139-out-OJ9ZI 2> /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-139-err-3Cd2E