#!/usr/bin/env perl

=head1 NAME

AddSpecificTypesAutogeneratedNameMetadataCvterms.pm

=head1 SYNOPSIS

mx-run ThisPackageName [options] -H hostname -D dbname -u username [-F]

this is a subclass of L<CXGN::Metadata::Dbpatch>
see the perldoc of parent class for more details.

=head1 DESCRIPTION
This patch adds plot_autogenerated_name_metadata and seedlot_autogenerated_name_metadata project_property cvterms and changes autogenerated_name_metadata to transformant_autogenerated_name_metadata.
This subclass uses L<Moose>. The parent class uses L<MooseX::Runnable>

=head1 AUTHOR

Titima Tantikanjana<tt15@cornell.edu>

=head1 COPYRIGHT & LICENSE

Copyright 2010 Boyce Thompson Institute for Plant Research

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut


package AddSpecificTypesAutogeneratedNameMetadataCvterms;

use Moose;
use Bio::Chado::Schema;
use Try::Tiny;
use SGN::Model::Cvterm;

extends 'CXGN::Metadata::Dbpatch';


has '+description' => ( default => <<'' );
Description of this patch goes here

has '+prereq' => (
    default => sub {
        ['AddTransformationAndTrackingCvterms'],
    },

);

sub patch {
    my $self=shift;

    print STDOUT "Executing the patch:\n " .   $self->name . ".\n\nDescription:\n  ".  $self->description . ".\n\nExecuted by:\n " .  $self->username . " .";

    print STDOUT "\nChecking if this db_patch was executed before or if previous db_patches have been executed.\n";

    print STDOUT "\nExecuting the SQL commands.\n";
    my $schema = Bio::Chado::Schema->connect( sub { $self->dbh->clone } );

    #change autogenerated_name_metadata project_property to transformant_autogenerated_name_metadata

	print STDERR "UPDATING CV TERM...\n";

	my $autogenerated_name_metadata_cvterm =  SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property');

	$autogenerated_name_metadata_cvterm->update( { name => 'transformant_autogenerated_name_metadata' } );

    print STDERR "INSERTING CV TERMS...\n";

    my $terms = {
        'project_property' => [
            'plot_autogenerated_name_metadata',
            'seedlot_autogenerated_name_metadata',
        ],
    };

    foreach my $t (keys %$terms){
        foreach (@{$terms->{$t}}){
            $schema->resultset("Cv::Cvterm")->create_with({
                name => $_,
                cv => $t
            });
        }
    }

    print "You're done!\n";

}


####
1; #
####
