#!/usr/bin/env perl


=head1 NAME

 ModifyNameMetadataStructure

=head1 SYNOPSIS

mx-run ModifyNameMetadataStructure [options] -H hostname -D dbname -u username [-F]

this is a subclass of L<CXGN::Metadata::Dbpatch>
see the perldoc of parent class for more details.

=head1 DESCRIPTION
This patch changes autogenerated name metadata structure to use name type as first level key
This subclass uses L<Moose>. The parent class uses L<MooseX::Runnable>

=head1 AUTHOR

Titima Tantikanjana<tt15@cornell.edu>

=head1 COPYRIGHT & LICENSE

Copyright 2010 Boyce Thompson Institute for Plant Research

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut


package ModifyNameMetadataStructure;

use Moose;
use Bio::Chado::Schema;
use Try::Tiny;
use SGN::Model::Cvterm;
use JSON;
use Data::Dumper;
use MooseX::FollowPBP;
use Moose::Util::TypeConstraints;


extends 'CXGN::Metadata::Dbpatch';


has '+description' => ( default => <<'' );
This patch changes data structure of name metadata to use name type as the first level key.

has '+prereq' => (
	default => sub {
        [],
    },

  );

sub patch {
    my $self=shift;

    print STDOUT "Executing the patch:\n " .   $self->name . ".\n\nDescription:\n  ".  $self->description . ".\n\nExecuted by:\n " .  $self->username . " .";

    print STDOUT "\nChecking if this db_patch was executed before or if previous db_patches have been executed.\n";

    print STDOUT "\nExecuting the SQL commands.\n";
    my $schema = Bio::Chado::Schema->connect( sub { $self->dbh->clone } );


    my $autogenerated_name_metadata_cvterm_id = SGN::Model::Cvterm->get_cvterm_row($schema, 'autogenerated_name_metadata', 'project_property')->cvterm_id();

	my $projectprop_rows = $schema->resultset("Project::Projectprop")->search({ type_id=> $autogenerated_name_metadata_cvterm_id });
	my $num_projectprop_rows = $projectprop_rows->count();
	if ($num_projectprop_rows > 0) {
	    while (my $each_row = $projectprop_rows->next()){
			my %old_name_metadata_hash = ();
		    my %new_data_structure = ();
		    print STDERR "NEW DATA STRUCTURE 1 =".Dumper(\%new_data_structure)."\n";
		    my $old_name_metadata_string = $each_row->value();
			print STDERR "OLD STRING =".Dumper($old_name_metadata_string)."\n";
		    my $old_name_metadata_hash_ref = decode_json $old_name_metadata_string;
			%old_name_metadata_hash = %$old_name_metadata_hash_ref;
			print STDERR "OLD HASH =".Dumper(\%old_name_metadata_hash)."\n";
            foreach my $format_name (keys %old_name_metadata_hash) {
				my $name_type = $old_name_metadata_hash{$format_name}{'name_type'};
				$new_data_structure{$name_type}{$format_name} = $old_name_metadata_hash{$format_name};
			}
			print STDERR "NEW DATA STRUCTURE 2 =".Dumper(\%new_data_structure)."\n";

			my $new_name_metadata_string = encode_json \%new_data_structure;
			$each_row->update({value=>$new_name_metadata_string});
	    }
    }


    print "You're done!\n";
}


####
1; #
####
