use strict;
use CXGN::Page;
my $page=CXGN::Page->new('call_for_BACS.html','html2pl converter');
$page->header('Questionnaire for BAC informations from other group:');
print<<END_HEREDOC;

<div class="Section1">
<center>
<h2>Call for anchored BACs</h2>
<table summary="" width="80\%" align="center">
<tr>
<td>
<p>Over the coming
decade the International Solanaceae Genome Project (SOL) will
create a coordinated network of knowledge about the Solanaceae
family. The first goal for the SOL project is to sequence the
gene-rich euchromatin in the tomato genome, which will serve as a
reference genome for other Solanaceae and related plant taxa.</p>

<p>Currently, we are working on integrating the high density genetic
map, based on an <em>L. esculentum</em> x <em>L. pennellii</em>
F2 population (referred to as the F2.2000
population), with the BAC physical map, which was generated by Dr.
Wing's group at the AGI. We will have about 2000 'seed BACs' that
are anchored onto the genetic map and will be used for the
beginning of tomato sequencing project. Since we have a large
Solanaceae community, some of you might already have worked on your
favorite BACs that were isolated with markers from the genetic map.
The anchoring information of your BACs would greatly increase the
number of 'seed BACs'. If you have difficulty to sequence your
favorite BACs, this might be a good opportunity to <strong>sequence your
BACs without any extra costs if it is already known to be anchored
via one or more markers on the genetic map. All you
need to do is to send the BAC related information (which genetic marker(s) were used
to isolate the BAC(s)), as listed in the attached file and in the
example case, and your BAC clones to us.</strong> We will make all the possible efforts to
sequence your BACs in a timely manner, although we don't guarantee
this. Please note that we are not expecting any co-authorship on
your future publications, but acknowledgement of our effort will be
appreciated. All the sequences will be deposited to the
<a href="index.pl">SGN</a> database and
GenBank as part of the SOL sequencing project.</p>

<p>In order to better
serve our community and finish the sequencing project efficiently,
we are calling for the submission of anchored BAC clones from the
LE_HBA library, which was made from <em>L. esculentum</em> cv. Heinz 1706.</p>

<p>If you have comments
or problems, please contact <a href="mailto:lam87\@cornell.edu">Lukas Mueller</a> or
<a href="mailto:yw84\@cornell.edu">Eileen Wang</a>.</p>

<p>Please use the form below to request your BAC to be sequenced.
An example form is provided for help.</p>

<p><a href="/static_content/solanaceae-project/bac_info.txt">BAC Submission Form</a></p>
<p><a href="/static_content/solanaceae-project/bac_info_example.txt">Example Form</a></p>

</td>
</tr>
</table>
</center>
 
</div>
END_HEREDOC
$page->footer();
