---
abstract: 'Next-generation Mason view for Catalyst'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Sebastian Willert <willert@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-HTML-Mason
requires:
  Catalyst: 5.8000_01
  Data::Visitor: 0
  HTML::Mason: 0
  Moose: 0
  MooseX::Types: 0
  MooseX::Types::Structured: 0
  Test::More: 0.88
  Try::Tiny: 0
  namespace::autoclean: 0
version: 0.01
