
use strict;

use lib 't/lib';

use Test::More;
use SGN::Test::WWW::WebDriver;
use SGN::Test::Fixture;
use File::Spec::Functions qw / catfile catdir/;

my $d = SGN::Test::WWW::WebDriver->new();
my $f = SGN::Test::Fixture->new();

`rm -r /tmp/localhost/`;

$d->while_logged_in_as("submitter", sub {

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="34 clones"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(20);

    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops);
    sleep(40);
    $d->find_element_ok('//img[@id="k-means-plot-list_19-genotype-k-4-gp-1"]', 'xpath', 'check k-means plot')->click();
    sleep(5);

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(3);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="60 plot naccri"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(20);
    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops);
    sleep(5);
    $d->find_element_ok('//img[@id="k-means-plot-list_14-phenotype-k-4"]', 'xpath', 'check k-means plot')->click();
    sleep(5);

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(3);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="Trials list"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(60);
    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops);  
    $d->find_element_ok('//img[@id="k-means-plot-list_10-genotype-k-4-gp-1"]', 'xpath', 'check k-means plot')->click();
    sleep(5);
  

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(3);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="Trials list"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(60);
    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops);  
    $d->find_element_ok('//img[@id="k-means-plot-list_10-phenotype-k-4"]', 'xpath', 'check k-means plot')->click();
    sleep(5);

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(3);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="two trials dataset"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(60);
    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops);  
    $d->find_element_ok('//img[@id="k-means-plot-dataset_11-genotype-k-4-gp-1"]', 'xpath', 'plot displayed')->click();    
    sleep(5);

    $d->get_ok('/cluster/analysis', 'cluster home page');     
    sleep(3);
    $d->find_element_ok('//select[@id="cluster_genotypes_list_select"]/option[text()="two trials dataset"]', 'xpath', 'select clones list')->click();
    sleep(5);
    $d->find_element_ok('//input[@value="Go"]', 'xpath', 'go btn')->click();
    sleep(5);   
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(1);
    $d->find_element_ok('Run Cluster', 'partial_link_text', 'run cluster')->click();
    sleep(60);
    my $sel_pops = $d->find_element('//*[contains(text(), "Select a")]', 'xpath', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -10);", $sel_pops); 
    sleep(5);
    $d->find_element_ok('//img[@id="k-means-plot-dataset_11-phenotype-k-4"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);

    
    $d->get_ok('/breeders/trial/139', 'trial detail home page');     
    sleep(5);
    my $analysis_tools = $d->find_element('Analysis Tools', 'partial_link_text', 'toogle analysis tools');
    my $elem = $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-50);", $analysis_tools);
    sleep(5);    
    $d->find_element_ok('Analysis Tools', 'partial_link_text', 'toogle analysis tools')->click();
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(60);
    $d->find_element_ok('//img[@id="k-means-plot-139-phenotype-k-5"]', 'xpath', 'plot displayed')->click();  
    sleep(5);

    my $analysis_tools = $d->find_element('cluster_canvas', 'id', 'toogle analysis tools');
    my $elem = $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-300);", $analysis_tools);
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(1);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(1);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(1);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(60);
    $d->find_element_ok('//img[@id="k-means-plot-139-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();
    sleep(2);
  
    
    $d->get_ok('/solgs', 'solgs homepage');
    sleep(4);
    my $solgs_data = $f->config->{basepath} . "/t/data/solgs/";  
    `cp -r $solgs_data /tmp/localhost/GBSApeKIgenotypingv4/`;
    sleep(10);  
  
    $d->get_ok('solgs/traits/all/population/139/traits/1971973596/gp/1', 'models page');
    sleep(5);
   
    my $sel_pops = $d->find_element('Predict', 'partial_link_text', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -600);", $sel_pops);
    sleep(5);
    $d->find_element_ok('list_type_selection_pops_list_select', 'id', 'select clones list menu')->click();
    sleep(5);
    my $dataset = $d->find_element_ok('//div[@id="list_type_selection_pops_list"]/select[@id="list_type_selection_pops_list_select"]/option[text()="Dataset Kasese Clones"]', 'xpath', 'select dataset sel pop');
    $dataset->click();
    sleep(5);
    
    my $sel_pops = $d->find_element('Predict', 'partial_link_text', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -200);", $sel_pops);
    
    $d->find_element_ok('//div[@id="list_type_selection_pop_load"]/input[@value="Go"]', 'xpath', 'select list sel pop')->click();
    sleep(5);
    $d->find_element_ok('list_type_selection_pops_list_select', 'id', 'select clones list menu')->click();
     sleep(5);
    my $list = $d->find_element_ok('//div[@id="list_type_selection_pops_list"]/select[@id="list_type_selection_pops_list_select"]/option[text()="34 clones"]', 'xpath', 'select list sel pop');
    $list->click();
    sleep(5);
   
    my $sel_pops = $d->find_element('Predict', 'partial_link_text', 'scroll up');
    my $elem =$d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0, -100);", $sel_pops);
    $d->find_element_ok('//div[@id="list_type_selection_pop_load"]/input[@value="Go"]', 'xpath', 'select list sel pop')->click();
     sleep(15);
    
    my $cor = $d->find_element('Genetic correlation', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $cor);
    sleep(5); 
    $d->find_element_ok('si_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);  
    $d->find_element_ok('//dl[@class="si_dropdown"]/dd/ul/li/a[text()="Kasese solgs trial"]', 'xpath', 'select trial type tr pop')->click();
    sleep(3);
    $d->find_element_ok('DMCP', 'id', 'rel wt 1st')->send_keys(3);
    sleep(5);
    $d->find_element_ok('FRW', 'id', 'rel wt 2st')->send_keys(5);
    sleep(5);
    $d->find_element_ok('calculate_si', 'id',  'calc selection index')->click();
    sleep(30);

    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="34 clones"]', 'xpath', 'select list sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(10);
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(50);
    $d->find_element_ok('//img[@id="k-means-plot-139-list_19-traits-1971973596-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(10);
 
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="34 clones"]', 'xpath', 'select list sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="GEBV"]', 'xpath', 'select gebv')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-list_19-traits-1971973596-gebv-k-5"]', 'xpath', 'check k-means plot')->click();
    sleep(3);
    
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="Dataset Kasese Clones"]', 'xpath', 'select dataset sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('//img[@id="k-means-plot-139-dataset_4-traits-1971973596-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(3);

    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="Dataset Kasese Clones"]', 'xpath', 'select dataset sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="GEBV"]', 'xpath', 'select gebv')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-dataset_4-traits-1971973596-gebv-k-5"]', 'xpath', 'check k-means plot')->click();  
    sleep(3);
    
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    my $elem = $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="Kasese solgs trial"]', 'xpath', 'select trial tr pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select ghenotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-traits-1971973596-phenotype-k-5"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);

    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="Kasese solgs trial"]', 'xpath', 'select trial tr pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-traits-1971973596-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();
    sleep(5);

    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="Kasese solgs trial"]', 'xpath', 'select trial tr pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="GEBV"]', 'xpath', 'select gebv')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-traits-1971973596-gebv-k-5"]', 'xpath', 'check k-means plot')->click();  

    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="trial2 NaCRRI"]', 'xpath', 'select trial sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-141-traits-1971973596-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);


    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="trial2 NaCRRI"]', 'xpath', 'select trial sel pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="GEBV"]', 'xpath', 'select gebv')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-141-traits-1971973596-gebv-k-5"]', 'xpath', 'check k-means plot')->click();  
    sleep(3);
    
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_dropdown', 'class', 'select list sl pop')->click();
    sleep(3);
    $d->find_element_ok('//dl[@class="cluster_dropdown"]/dd/ul/li/a[text()="139-DMCP-3-FRW-5-traits-1971973596"]', 'xpath', 'select sel index pop')->click();
    sleep(3);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('5');
    sleep(2);
    $d->find_element_ok('selection_proportion', 'id', 'select k number')->send_keys('15');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-139-15-traits-1971973596-genotype-k-5-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);
  
    $d->get_ok('/solgs/trait/70666/population/139/gp/1', 'open model page');
    sleep(2);
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-70666-phenotype-k-4"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);
	
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-200);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-139-70666-genotype-k-4-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);

    $d->get_ok('/solgs/model/combined/populations/2804608595/trait/70741/gp/1', 'open combined trials model page');
    sleep(2);
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-100);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Phenotype"]', 'xpath', 'select phenotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-2804608595-70741-phenotype-k-4"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);
	
    my $clustering = $d->find_element('Clustering', 'partial_link_text', 'scroll up');
    $d->driver->execute_script( "arguments[0].scrollIntoView(true);window.scrollBy(0,-100);", $clustering);
    sleep(5);
    $d->find_element_ok('cluster_type_select', 'id', 'select k-means')->send_keys('K-means');
    sleep(2);
    $d->find_element_ok('//select[@id="cluster_data_type_select"]/option[text()="Genotype"]', 'xpath', 'select genotype')->click();
    sleep(2);
    $d->find_element_ok('k_number', 'id', 'clear k number')->clear();
    $d->find_element_ok('k_number', 'id', 'select k number')->send_keys('4');
    sleep(2);
    $d->find_element_ok('run_cluster', 'id', 'run cluster')->click();
    sleep(20);
    $d->find_element_ok('//img[@id="k-means-plot-2804608595-70741-genotype-k-4-gp-1"]', 'xpath', 'check k-means plot')->click();  
    sleep(5);
        
});





done_testing();
