---
Title: Anova implementation
output: html_document
author: Isaak Y Tecle
---

A draft for implementation of ANOVA on the trial pages. 
Anyone interested is welcome to implement any of the parts or modify this document.

## Controller
- function a query for phenotype data file
- function for checking if the trial has experimental design
- function for, if data appropriate for anova, creating anova output files
- function to call an R script for the anova analysis
- function to proces R anova output for display

## R script
- Reads in phenotype data from file
- Saves output file names
- Does filtering and preprocessing of data
- Has run-time tests
- Runs anova
- Writes output to files

## Mason
- Has a button to call anova analysis
- On button click js function to request analysis
- Display template for anova table
- Link to download anova table, BLUES, BLUPS and model summary

## JavaScript
- onclick, call phenotype data querying function in lib/SGN/Controller/Anova.pm
- calls a function to check if data is appropriate for ANOVA
- calls for ANOVA analysis
- calls for trait selection menu
- On analysis success, display output, links to download output
- On failure, give informative feedback
