#!/bin/bash

mx-run solGS::queryJobs  --data_type genotype --population_type list --args_file /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/geno-data-args_file-list_24-JKXre > /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-list_24-out-KLcOh 2> /export/prod/tmp/localhost/GBSApeKIgenotypingv4/solgs/tempfiles/genotype-data-query-list_24-err-PLaSJ