# Re-usable workflow to run tests
name: Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '*.md'

jobs:

  test_breedbase:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subtest_key:
          - unit
          - unit_fixture
          - unit_mech
          - selenium2_list
          - selenium2_trial
          - selenium2_dataset
          - selenium2_authenticate
          - selenium2_breeders
          - selenium2_onto
          - selenium2_search
          - selenium2_stock
          - selenium2_tools
    steps:

      # -----------------------------------------------------------------------
      # Setup

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: false
          large-packages: false
          swap-storage: false

      - name: Checkout breedbase_dockerfile
        uses: actions/checkout@v6
        with:
          repository: bff-afirms/breedbase_dockerfile
          ref: bff-afirms
          submodules: recursive
      
      - name: Cleanup breedbase_dockerfile
        run: rm -rf cxgn/sgn

      - name: Checkout sgn
        uses: actions/checkout@v6
        with:
          path: 'cxgn/sgn'

      - name: Setup
        run: ./setup

      - name: Build supporting images
        run: docker compose -f compose.testing.yml build --no-cache

      # -----------------------------------------------------------------------
      # Testing

      # use -s flag to show stderr
      - name: Run quick setup
        run: |
          ./run_test -s t/unit/CXGN/String
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run unit tests
        if: ${{ matrix.subtest_key == 'unit' }}
        run: |
          ./run_test t/unit
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run fixture tests
        if: ${{ matrix.subtest_key == 'unit_fixture' }}
        run: |
          ./run_test t/unit_fixture
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run mech tests
        if: ${{ matrix.subtest_key == 'unit_mech' }}
        run: |
          ./run_test t/unit_mech
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      # Run all selenium tests individually to avoid solgs for now
      - name: Run selenium tests lists
        if: ${{ matrix.subtest_key == 'selenium2_list' }}
        run: |
          ./run_test t/selenium2/01_list
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests trial
        if: ${{ matrix.subtest_key == 'selenium2_trial' }}
        run: |
          ./run_test t/selenium2/02_trial
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests dataset
        if: ${{ matrix.subtest_key == 'selenium2_dataset' }}
        run: |
          ./run_test t/selenium2/03_dataset
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests authenticate
        if: ${{ matrix.subtest_key == 'selenium2_authenticate' }}
        run: |
          ./run_test t/selenium2/authenticate
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests breeders
        if: ${{ matrix.subtest_key == 'selenium2_breeders' }}
        run: |
          ./run_test t/selenium2/breeders
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests onto
        if: ${{ matrix.subtest_key == 'selenium2_onto' }}
        run: |
          ./run_test t/selenium2/onto
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests search
        if: ${{ matrix.subtest_key == 'selenium2_search' }}
        run: |
          ./run_test t/selenium2/search
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests stock
        if: ${{ matrix.subtest_key == 'selenium2_stock' }}
        run: |
          ./run_test t/selenium2/stock
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests tools
        if: ${{ matrix.subtest_key == 'selenium2_tools' }}
        run: |
          ./run_test t/selenium2/tools
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            data/selenium/screenshots/*
          retention-days: 3