# Re-usable workflow to run tests
name: Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:

  test_breedbase:
    runs-on: ubuntu-latest
    steps:

      # -----------------------------------------------------------------------
      # Setup

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: false
          large-packages: false
          swap-storage: false

      - name: Checkout breedbase_dockerfile
        uses: actions/checkout@v6
        with:
          repository: bff-afirms/breedbase_dockerfile
          ref: bff-afirms
          submodules: recursive
      
      - name: Cleanup breedbase_dockerfile
        run: rm -rf cxgn/sgn

      - name: Checkout sgn
        uses: actions/checkout@v6
        with:
          path: 'cxgn/sgn'

      - name: Setup
        run: ./setup

      - name: Build supporting images
        run: docker compose -f compose.testing.yml build --no-cache

      # -----------------------------------------------------------------------
      # Testing

      # use -s flag to show stderr
      - name: Run quick setup
        run: |
          ./run_test -s t/unit/CXGN/String
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run unit tests
        run: |
          ./run_test t/unit
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run fixture tests
        run: |
          ./run_test t/unit_fixture
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run mech tests
        run: |
          ./run_test t/unit_mech
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      # Run all selenium tests individually to avoid solgs for now
      - name: Run selenium tests lists
        run: |
          ./run_test t/selenium2/01_list
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests trial
        run: |
          ./run_test t/selenium2/02_trial
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests dataset
        run: |
          ./run_test t/selenium2/03_dataset
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests authenticate
        run: |
          ./run_test t/selenium2/authenticate
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests breeders
        run: |
          ./run_test t/selenium2/breeders
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests onto
        run: |
          ./run_test t/selenium2/onto
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests search
        run: |
          ./run_test t/selenium2/search
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests stock
        run: |
          ./run_test t/selenium2/stock
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')

      - name: Run selenium tests tools
        run: |
          ./run_test t/selenium2/tools
          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')